# Generated by Django 2.0.2 on 2018-03-05 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doorway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the doorway', max_length=255, verbose_name='doorway name')),
            ],
        ),
        migrations.CreateModel(
            name='DPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doorway', models.ForeignKey(blank=True, help_text='Which doorway is this DPU installed on currently', null=True, on_delete=django.db.models.deletion.SET_NULL, to='interview.Doorway', verbose_name='installed on doorway')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='The date and time this measurement was taken', verbose_name='measurement timestamp')),
                ('direction', models.BooleanField(help_text='The direction the DPU was passed', verbose_name='measurement direction')),
                ('doorway', models.ForeignKey(help_text='Which doorway did this measurement come from at the time', on_delete=django.db.models.deletion.CASCADE, to='interview.Doorway', verbose_name='measurement doorway')),
                ('dpu', models.ForeignKey(blank=True, help_text='Which dpu took this measurement at the time', null=True, on_delete=django.db.models.deletion.SET_NULL, to='interview.DPU', verbose_name='measurement dpu')),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the space or room', max_length=255, verbose_name='space name')),
            ],
        ),
        migrations.AddField(
            model_name='dpu',
            name='space_minus',
            field=models.ForeignKey(blank=True, help_text='Which space or room does a -1 measurement mean movement into', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dpus_minus', to='interview.Space', verbose_name='minus measures into space'),
        ),
        migrations.AddField(
            model_name='dpu',
            name='space_plus',
            field=models.ForeignKey(blank=True, help_text='Which space or room does a +1 measurement mean movement into', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dpus_plus', to='interview.Space', verbose_name='plus measures into space'),
        ),
        migrations.AddField(
            model_name='doorway',
            name='space_in',
            field=models.ForeignKey(blank=True, help_text='Which space or room does the doorway open into', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doorways_in', to='interview.Space', verbose_name='space to doorway opens into'),
        ),
        migrations.AddField(
            model_name='doorway',
            name='space_out',
            field=models.ForeignKey(blank=True, help_text='Which space or room does the doorway open out of', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doorways_out', to='interview.Space', verbose_name='space to doorway opens out of'),
        ),
    ]
