# Generated by Django 2.0.2 on 2018-03-05 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='The date and time the person passed', verbose_name='timestamp')),
                ('direction', models.BooleanField(help_text='The direction the DPU was passed', verbose_name='direction')),
                ('doorway', models.ForeignKey(help_text='Which doorway did the person pass through', on_delete=django.db.models.deletion.CASCADE, to='interview.Doorway', verbose_name='doorway')),
            ],
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='doorway',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='dpu',
        ),
        migrations.AlterField(
            model_name='dpu',
            name='space_minus',
            field=models.ForeignKey(blank=True, help_text='Which space or room does a -1 measurement mean passing into', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dpus_minus', to='interview.Space', verbose_name='minus measures into space'),
        ),
        migrations.AlterField(
            model_name='dpu',
            name='space_plus',
            field=models.ForeignKey(blank=True, help_text='Which space or room does a +1 measurement mean passing into', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dpus_plus', to='interview.Space', verbose_name='plus measures into space'),
        ),
        migrations.DeleteModel(
            name='Measurement',
        ),
        migrations.AddField(
            model_name='pass',
            name='dpu',
            field=models.ForeignKey(blank=True, help_text='Which DPU measured the passing at the time', null=True, on_delete=django.db.models.deletion.SET_NULL, to='interview.DPU', verbose_name='DPU'),
        ),
    ]
