# Generated by Django 2.0.2 on 2018-03-05 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_pass_spaces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pass',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='pass',
            name='dpu',
        ),
        migrations.AddField(
            model_name='pass',
            name='space_in',
            field=models.ForeignKey(blank=True, help_text='Which space or room did the person pass into', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='interview.Space', verbose_name='space passed into'),
        ),
        migrations.AddField(
            model_name='pass',
            name='space_out',
            field=models.ForeignKey(blank=True, help_text='Which space or room did the person pass out of', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exits', to='interview.Space', verbose_name='space passed out of'),
        ),
        migrations.AlterField(
            model_name='doorway',
            name='space_in',
            field=models.ForeignKey(blank=True, help_text='Which space or room does the doorway open into', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doorways_in', to='interview.Space', verbose_name='space the doorway opens into'),
        ),
        migrations.AlterField(
            model_name='doorway',
            name='space_out',
            field=models.ForeignKey(blank=True, help_text='Which space or room does the doorway open out of', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doorways_out', to='interview.Space', verbose_name='space the doorway opens out of'),
        ),
        migrations.AlterField(
            model_name='pass',
            name='timestamp',
            field=models.DateTimeField(help_text='The date and time this measurement was taken', verbose_name='measurement timestamp'),
        ),
    ]
